### PR TITLE
Update and rename sigmanautsalphapool.json to ErgoSigmanautsMiningPoo…

### PR DESCRIPTION
**Pull request by andrehafner**
changed json name from alpha and updated to final pools for low and high diff as well as tls and non tls
thanks so much guys!

### CODE REVIEW

**Comment by andrehafner** [comment]
Hi halo, what’s invalid/what should I fix? @HaloGenius

**Comment by andrehafner** [comment]
changed out FQDN for IP as some configs don't like the domain name.

**Comment by HaloGenius** [comment]
All file names should be in lowercase
Please keep file name in lowercase

**Comment by andrehafner** [comment]
changed titles to LC. Thanks so much HaloG! @HaloGenius

**Comment by HaloGenius** [comment]
@andrehafner You can use pretty name spelling in header `"pool"` section but file name should be in lowercase

**Comment by andrehafner** [comment]
thanks so much HaloG!

**Pull request merged**
