### PR TITLE
add new NEXA pool, simplify KASPA miners section to prototype

### PR DESCRIPTION
**Pull request by kid-alan**
@HaloGenius Hello, Halo!
Please consider this updates for a new Kryptex NEXA pool.

Thank you!

### CODE REVIEW

**Comment by maxmalysh** [comment]
@HaloGenius please merge this. We have hundreds of miners at pool.kryptex.com waiting for a fix of this issue.

Thank you!

**Comment by maxmalysh** [comment]
@HaloGenius we understand that you have lots of thing on your plate. However, this one is needed by thousands of our miners. Please merge this

 ♥️♥️♥️

**Comment by maxmalysh** [comment]
Thank you very much! 🖤

**Comment by kid-alan** [comment]
Many thanks! 🙏

**Pull request merged**
