### PR TITLE
Update for custom miner

### PR DESCRIPTION
**Pull request by metscoin**
Update for custom miner

### CODE REVIEW

**Comment by minershive** [comment]
i will accept it for now, but in future custom miners are discouraged to be added in templates because of the versions

**Comment by metscoin** [comment]
OK - I was just following the template used by Nicehash and trying to make it easy for my handful of miners since your new interface.

**Comment by Urgo** [comment]
@minershive any thoughts on creating something like http://download.hiveos.farm/custom/cryptodredge-latest.tar.gz that basically is just a symlink to the latest version on there to solve the need for putting versions in the template file?

**Comment by minershive** [comment]
Yes, working on this. We want to make a better repo for miners.

**Pull request merged**
