### PR TITLE
K1Pool added Etchash and Multialgo

### PR DESCRIPTION
**Pull request by k1pool**

### CODE REVIEW

**Comment by rewrewby** [comment]
Whats wrong with pull request?

**Comment by HaloGenius** [comment]
Yes sorry for the missing comment on the reason. This is a construction of two non-existent entities - a virtual algorithm and a virtual coin. At the moment, we cannot satisfy such a request because it affects the overall statistics.
If you have any suggestions on this matter, we listen to it.

**Comment by HaloGenius** [comment]
Please open new request to add ETC on EtcHash

**Comment by k1pool** [comment]
Got it, thanks.
https://github.com/minershive/hive-pooltemplates/pull/748

**Pull request closed without merging**
